import TesseraCore
import TesseraLayout
import TesseraTerminalCore
import TesseraTerminalInput

/// The semantic intent of a button action.
public enum ButtonRole: Equatable, Sendable {
  /// An action that destroys user data or otherwise needs emphasis.
  case destructive
}

/// The semantic inputs supplied to a ``ButtonStyle``.
public struct ButtonStyleConfiguration {
  /// The application-provided label.
  public let label: AnyView
  /// Whether the button is enabled.
  public let isEnabled: Bool
  /// Whether the button owns focus.
  public let isFocused: Bool
  /// Whether an activation key is currently held.
  public let isPressed: Bool
  /// The action's semantic role.
  public let role: ButtonRole?

  package init(
    label: AnyView,
    isEnabled: Bool,
    isFocused: Bool,
    isPressed: Bool,
    role: ButtonRole?
  ) {
    self.label = label
    self.isEnabled = isEnabled
    self.isFocused = isFocused
    self.isPressed = isPressed
    self.role = role
  }
}

/// A visual treatment for a Button that does not change activation semantics.
public protocol ButtonStyle {
  /// The view generated by this style.
  associatedtype Body: View

  /// Creates the style's view from current semantic state.
  @ViewBuilder func makeBody(configuration: ButtonStyleConfiguration) -> Body
}

/// Square-bracket chrome around a Button label.
public struct CompactButtonStyle: ButtonStyle {
  /// Creates the compact system style.
  public init() {}

  /// Creates compact square-bracket chrome for the current configuration.
  public func makeBody(configuration: ButtonStyleConfiguration) -> some View {
    _CompactButtonStyleBody(configuration: configuration)
  }
}

/// An unadorned Button label suitable for menus and sidebars.
public struct PlainButtonStyle: ButtonStyle {
  /// Creates the plain system style.
  public init() {}

  /// Creates an unadorned label for the current configuration.
  public func makeBody(configuration: ButtonStyleConfiguration) -> some View {
    _PlainButtonStyleBody(configuration: configuration)
  }
}

extension ButtonStyle where Self == CompactButtonStyle {
  /// The compact square-bracket system style.
  public static var compact: Self { Self() }
}

extension ButtonStyle where Self == PlainButtonStyle {
  /// The unadorned system style.
  public static var plain: Self { Self() }
}

package struct _AnyButtonStyle {
  private let makeBodyClosure: (ButtonStyleConfiguration) -> AnyView

  package init<Style: ButtonStyle>(_ style: Style) {
    makeBodyClosure = { configuration in
      AnyView(style.makeBody(configuration: configuration))
    }
  }

  package func makeBody(configuration: ButtonStyleConfiguration) -> AnyView {
    makeBodyClosure(configuration)
  }
}

private enum _ButtonStyleKey: EnvironmentKey {
  static var defaultValue: _AnyButtonStyle { _AnyButtonStyle(CompactButtonStyle()) }
}

extension EnvironmentValues {
  package var _buttonStyle: _AnyButtonStyle {
    get { self[_ButtonStyleKey.self] }
    set { self[_ButtonStyleKey.self] = newValue }
  }
}

extension View {
  /// Overrides the visual style of Buttons in this subtree.
  public func buttonStyle<Style: ButtonStyle>(_ style: Style) -> some View {
    environment(\._buttonStyle, _AnyButtonStyle(style))
  }
}

private struct _CompactButtonStyleBody: View {
  let configuration: ButtonStyleConfiguration

  var body: some View {
    EnvironmentReader { environment in
      let activeStyle = resolvedStyle(in: environment)
      let delimiterStyle = idleStyle(
        in: environment,
        fallback: environment.semanticStyles.secondary
      )
      let labelStyle = idleStyle(
        in: environment,
        fallback: environment.semanticStyles.primary
      )
      HStack(spacing: 0) {
        Text("[").style(configuration.isPressed ? activeStyle : delimiterStyle)
        configuration.label.style(configuration.isPressed ? activeStyle : labelStyle)
        Text("]").style(configuration.isPressed ? activeStyle : delimiterStyle)
      }
    }
  }

  private func idleStyle(in environment: EnvironmentValues, fallback: Style) -> Style {
    guard configuration.isEnabled else {
      return environment.semanticStyles.disabled
    }
    if configuration.isFocused {
      return environment.semanticStyles.focus
    }
    if configuration.role == .destructive {
      return environment.semanticStyles.destructive
    }
    return fallback
  }

  private func resolvedStyle(in environment: EnvironmentValues) -> Style {
    idleStyle(in: environment, fallback: environment.semanticStyles.primary)
  }
}

private struct _PlainButtonStyleBody: View {
  let configuration: ButtonStyleConfiguration

  var body: some View {
    EnvironmentReader { environment in
      configuration.label.style(resolvedStyle(in: environment))
    }
  }

  private func resolvedStyle(in environment: EnvironmentValues) -> Style {
    guard configuration.isEnabled else {
      return environment.semanticStyles.disabled
    }
    if configuration.isFocused {
      return environment.semanticStyles.focus
    }
    if configuration.role == .destructive {
      return environment.semanticStyles.destructive
    }
    return environment.semanticStyles.primary
  }
}

/// An application-controlled action with an arbitrary label.
public struct Button<Label: View>: View, _FocusAppearanceResponder {
  private let action: () -> Void
  private let label: Label
  private let role: ButtonRole?

  public var body: some View {
    EnvironmentReader { environment in
      _ButtonResponder(
        action: action,
        label: label,
        role: role,
        isEnabled: environment.isEnabled
      )
    }
  }

  /// Creates a button.
  public init(
    role: ButtonRole? = nil,
    action: @escaping () -> Void,
    @ViewBuilder label: () -> Label
  ) {
    self.action = action
    self.label = label()
    self.role = role
  }
}

private struct _ButtonResponder<Label: View>: View, _LayoutView, _ResponderView,
  _TerminalRequirementsView
{
  typealias Body = Never

  struct ResponderState {
    var pressedKey: KeyCode?
  }

  let action: () -> Void
  let label: Label
  let role: ButtonRole?
  let isEnabled: Bool

  package var _terminalRequirements: TerminalRequirements {
    TerminalRequirements(wantsKeyboardEnhancement: true)
  }

  package func _makeResponderState() -> ResponderState {
    ResponderState(pressedKey: nil)
  }

  package func _handleEvent(
    _ event: InputEvent,
    state: inout ResponderState,
    context: inout ResponderContext
  ) -> EventDisposition {
    guard context.isFocused, isEnabled, case .key(let key) = event
    else {
      return .ignored
    }

    switch key.code {
    case .enter, .character(" "):
      return handleActivationKey(key, state: &state, context: &context)
    case .escape:
      guard state.pressedKey != nil else {
        return .ignored
      }
      state.pressedKey = nil
      context.setNeedsDisplay()
      return .handled
    default:
      return .ignored
    }
  }

  package func _visitChildren(
    in environment: EnvironmentValues,
    environmentOverrides: [String],
    _ visit: (_ViewChild) -> Void
  ) {
    let configuration = ButtonStyleConfiguration(
      label: AnyView(label),
      isEnabled: environment.isEnabled,
      isFocused: environment.isFocused,
      isPressed: false,
      role: role
    )
    visit(
      _ViewChild(
        slot: .index(0),
        view: environment._buttonStyle.makeBody(configuration: configuration),
        environment: environment,
        environmentOverrides: environmentOverrides
      )
    )
  }

  package func _sizeThatFits(
    _ proposal: ProposedSize,
    subviews: _LayoutSubviewsProxy
  ) -> TerminalSize {
    guard subviews.count == 1 else {
      return TerminalSize(columns: 0, rows: 0)
    }
    return subviews[0].measure(proposal)
  }

  package func _placeSubviews(
    in bounds: Rect,
    proposal: ProposedSize,
    subviews: _LayoutSubviewsProxy
  ) {
    guard subviews.count == 1 else {
      return
    }
    subviews[0].place(
      bounds.origin,
      ProposedSize(width: bounds.size.columns, height: bounds.size.rows)
    )
  }

  private func handleActivationKey(
    _ key: Key,
    state: inout ResponderState,
    context: inout ResponderContext
  ) -> EventDisposition {
    guard key.modifiers.isEmpty else {
      return .ignored
    }

    switch key.kind {
    case .press:
      // Legacy terminals report only this event. A later enhanced release only clears the
      // transient press state, so the action remains exactly-once.
      state.pressedKey = key.code
      action()
      context.setNeedsDisplay()
      return .handled
    case .repeat:
      return .handled
    case .release:
      guard state.pressedKey == key.code else {
        return .ignored
      }
      state.pressedKey = nil
      context.setNeedsDisplay()
      return .handled
    }
  }
}

extension Button where Label == Text {
  /// Creates a button with a text label.
  public init(
    _ title: String,
    role: ButtonRole? = nil,
    action: @escaping () -> Void
  ) {
    self.action = action
    self.label = Text(title)
    self.role = role
  }
}
